# Setup
title:               'Emily's IDH Blog'
tagline:             'A collection of Digital Humanities thoughts.'
description:         'This is where I'll put all my blog posts.'
url:                 http://miller-emily.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Emily Miller
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
