# Setup
title:               A Spite Blog
tagline:             'I cannot believe it was one little letter'
description:         'But I ended up really liking Hyde'
url:                 https://miller-emily.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name: Emily Miller             
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
